/**
  * A list of email domains that are allowed to register accounts.
  * For now, only allow a small subsection of these during testing phase.
  */
export const allowedDomains = [
  /*
   * Municipalities
   */
  "boden.se",
  "borlange.se",
  "gavle.se",
  "hylte.se",
  "kalmar.se",
  "linkoping.se",
  "lulea.se",
  "pitea.se",
  "sundsvall.se",
  "tranas.se",
  "trosa.se",
  "varberg.se",
  // "ale.se",
  // "alingsas.se",
  // "almhult.se",
  // "alvdalen.se",
  // "alvesta.se",
  // "alvkarleby.se",
  // "alvsbyn.se",
  // "amal.se",
  // "aneby.se",
  // "ange.se",
  // "arboga.se",
  // "are.se",
  // "arjang.se",
  // "arjeplog.se",
  // "arvidsjaur.se",
  // "arvika.se",
  // "asele.se",
  // "askersund.se",
  // "astorp.se",
  // "atvidaberg.se",
  // "avesta.se",
  // "bastad.se",
  // "bengtsfors.se",
  // "berg.se",
  // "bjurholm.se",
  // "bjuv.se",
  // "bollebygd.se",
  // "bollnas.se",
  // "boras.se",
  // "borgholm.se",
  // "botkyrka.se",
  // "boxholm.se",
  // "bracke.se",
  // "bromolla.se",
  // "burlov.se",
  // "dalsed.se",
  // "danderyd.se",
  // "degerfors.se",
  // "dorotea.se",
  // "eda.se",
  // "ekero.se",
  // "eksjo.se",
  // "emmaboda.se",
  // "engelholm.se",
  // "enkoping.se",
  // "eskilstuna.se",
  // "eslov.se",
  // "essunga.se",
  // "fagersta.se",
  // "falkenberg.se",
  // "falkoping.se",
  // "falun.se",
  // "fargelanda.se",
  // "filipstad.se",
  // "finspang.se",
  // "flen.se",
  // "forshaga.se",
  // "gagnef.se",
  // "gallivare.se",
  // "gislaved.se",
  // "gnesta.se",
  // "gnosjo.se",
  // "gotene.se",
  // "gotland.se",
  // "grastorp.se",
  // "grums.se",
  // "gullspang.se",
  // "habo.se",
  // "habokommun.se",
  // "hagfors.se",
  // "hallsberg.se",
  // "hallstahammar.se",
  // "halmstad.se",
  // "hammaro.se",
  // "haninge.se",
  // "haparanda.se",
  // "harnosand.se",
  // "harryda.se",
  // "hassleholm.se",
  // "heby.se",
  // "hedemora.se",
  // "hellefors.se",
  // "helsingborg.se",
  // "herjedalen.se",
  // "herrljunga.se",
  // "hjo.se",
  // "hofors.se",
  // "hoganas.se",
  // "hogsby.se",
  // "hoor.se",
  // "horby.se",
  // "huddinge.se",
  // "hudiksvall.se",
  // "hultsfred.se",
  // "jarfalla.se",
  // "jokkmokk.se",
  // "jonkoping.se",
  // "kalix.se",
  // "karlsborg.se",
  // "karlshamn.se",
  // "karlskoga.se",
  // "karlskrona.se",
  // "karlstad.se",
  // "katrineholm.se",
  // "kavlinge.se",
  // "kil.se",
  // "kinda.se",
  // "kiruna.se",
  // "klippan.se",
  // "knivsta.se",
  // "koping.se",
  // "kramfors.se",
  // "kristianstad.se",
  // "kristinehamn.se",
  // "krokom.se",
  // "kumla.se",
  // "kungalv.se",
  // "kungsbacka.se",
  // "kungsor.se",
  // "laholm.se",
  // "landskrona.se",
  // "laxa.se",
  // "lekeberg.se",
  // "leksand.se",
  // "lerum.se",
  // "lessebo.se",
  // "lidingo.se",
  // "lidkoping.se",
  // "lillaedet.se",
  // "lindesberg.se",
  // "ljungby.se",
  // "ljusdal.se",
  // "ljusnarsberg.se",
  // "lomma.se",
  // "ludvika.se",
  // "lund.se",
  // "lycksele.se",
  // "lysekil.se",
  // "mala.se",
  // "malmo.se",
  // "malung-salen.se",
  // "mariestad.se",
  // "mark.se",
  // "markaryd.se",
  // "mellerud.se",
  // "mjolby.se",
  // "molndal.se",
  // "monsteras.se",
  // "mora.se",
  // "morbylanga.se",
  // "motala.se",
  // "mullsjo.se",
  // "munkedal.se",
  // "munkfors.se",
  // "nacka.se",
  // "nassjo.se",
  // "nora.se",
  // "norberg.se",
  // "nordanstig.se",
  // "nordmaling.se",
  // "norrkoping.se",
  // "norrtalje.se",
  // "norsjo.se",
  // "nybro.se",
  // "nykoping.se",
  // "nykvarn.se",
  // "nynashamn.se",
  // "ockelbo.se",
  // "ockero.se",
  // "odeshog.se",
  // "olofstrom.se",
  // "orebro.se",
  // "orkelljunga.se",
  // "ornskoldsvik.se",
  // "orsa.se",
  // "orust.se",
  // "osby.se",
  // "oskarshamn.se",
  // "osteraker.se",
  // "ostersund.se",
  // "osthammar.se",
  // "ostragoinge.se",
  // "ovanaker.se",
  // "overkalix.se",
  // "overtornea.se",
  // "oxelosund.se",
  // "pajala.se",
  // "partille.se",
  // "perstorp.se",
  // "ragunda.se",
  // "rattvik.se",
  // "robertsfors.se",
  // "ronneby.se",
  // "saffle.se",
  // "sala.se",
  // "salem.se",
  // "sandviken.se",
  // "sater.se",
  // "savsjo.se",
  // "sigtuna.se",
  // "simrishamn.se",
  // "sjobo.se",
  // "skara.se",
  // "skelleftea.se",
  // "skinnskatteberg.se",
  // "skovde.se",
  // "skurup.se",
  // "smedjebacken.se",
  // "soderhamn.se",
  // "soderkoping.se",
  // "sodertalje.se",
  // "solleftea.se",
  // "sollentuna.se",
  // "solna.se",
  // "solvesborg.se",
  // "sorsele.se",
  // "sotenas.se",
  // "stadshuset.goteborg.se",
  // "staffanstorp.se",
  // "stenungsund.se",
  // "stockholm.se",
  // "storfors.se",
  // "storuman.se",
  // "strangnas.se",
  // "stromstad.se",
  // "stromsund.se",
  // "sundbyberg.se",
  // "sunne.se",
  // "surahammar.se",
  // "svalov.se",
  // "svedala.se",
  // "svenljunga.se",
  // "taby.se",
  // "tanum.se",
  // "tibro.se",
  // "tidaholm.se",
  // "tierp.se",
  // "timra.se",
  // "tingsryd.se",
  // "tjorn.se",
  // "tomelilla.se",
  // "toreboda.se",
  // "torsas.se",
  // "torsby.se",
  // "tranemo.se",
  // "trelleborg.se",
  // "trollhattan.se",
  // "tyreso.se",
  // "uddevalla.se",
  // "ulricehamn.se",
  // "umea.se",
  // "upplands-bro.se",
  // "upplandsvasby.se",
  // "uppsala.se",
  // "uppvidinge.se",
  // "vadstena.se",
  // "vaggeryd.se",
  // "valdemarsvik.se",
  // "vallentuna.se",
  // "vanersborg.se",
  // "vannas.se",
  // "vansbro.se",
  // "vara.se",
  // "vargarda.se",
  // "varmdo.se",
  // "varnamo.se",
  // "vasteras.se",
  // "vastervik.se",
  // "vaxholm.se",
  // "vaxjo.se",
  // "vellinge.se",
  // "vetlanda.se",
  // "vilhelmina.se",
  // "vimmerby.se",
  // "vindeln.se",
  // "vingaker.se",
  // "ydre.se",
  // "ystad.se",


  /*
   * Regions
   */
  // "gotland.se",
  // "kronoberg.se",
  // "norrbotten.se",
  // "regionblekinge.se",
  // "regiondalarna.se",
  // "regiongavleborg.se",
  // "regionhalland.se",
  // "regionjh.se",
  // "regionkalmar.se",
  // "regionorebrolan.se",
  // "regionostergotland.se",
  // "regionsormland.se",
  // "regionstockholm.se",
  // "regionuppsala.se",
  // "regionvarmland.se",
  // "regionvasterbotten.se",
  // "regionvastmanland.se",
  // "rjl.se",
  // "rvn.se",
  // "skane.se",
  // "vgregion.se",


  /*
   * Energy Agencies
   */
  "bodensenergi.se",
  // "energikontor.se",
  // "energikontornorr.se",
  // "energikontorsyd.se",
  // "energikontorvast.se",
  // "gotland.se",
  // "regiondalarna.se",
  // "regiongavleborg.se",
  // "regionhalland.se",
  // "regionjh.se",
  // "regionorebrolan.se",
  // "regionostergotland.se",
  // "regionvarmland.se",
  // "rjl.se",
  // "rvn.se",
  // "storsthlm.se",


  /*
   * Other
   */
  "differ.se",
  "internetstiftelsen.se",
  "ltu.se",
  "postkodstiftelsen.se",
  "ri.se",
  "sustainable-action.org",
  "sustainable-action.ngo",
  "viegandmaagoe.dk",
  // "lansstyrelsen.se",
  // "stuns.se",
];

/**
 * Email domains that enroll into another domain's org at signup.
 * In-code alias so both SAF addresses land in the same org without touching
 * the database (the org row carries the canonical domain).
 * NOTE: "permanent temporary" solution; revisit if SAF ever becomes two real orgs.
 */
export const orgDomainAliases: Record<string, string> = {
  "sustainable-action.ngo": "sustainable-action.org",
};