name: transition-planner

services:
  prod:
    image: ghcr.io/sustainable-action-foundation/eco-planner:latest
    pull_policy: always
    networks:
      - default
    ports:
      - "8081:8081"
    environment:
      # Database connection string
      - DATABASE_URL=${DATABASE_URL:?error}
      # Iron session cookie encryption password
      - IRON_SESSION_PASSWORD=${IRON_SESSION_PASSWORD:?error}
      # Used to connect mailClient to SMTP server
      - MAIL_HOST=${MAIL_HOST:?error}
      - MAIL_USER=${MAIL_USER:?error}
      - MAIL_PASSWORD=${MAIL_PASSWORD:?error}
      # Used for links in emails and as canonical url in meta tags
      - BASE_URL=${BASE_URL}
    # Wait for database to start, then reset and seed the database and start the server
    command: sh -c 'HOSTNAME="0.0.0.0" node server.js'