name: eco-planner:test

services:
  db:
    build:
      context: .
      dockerfile: docker/testdb.Dockerfile
    networks:
      - test_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin" ]
      interval: 2s
      timeout: 20s
      retries: 10

  web:
    image: ecoplanner:web
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - test_network
    ports:
      - 127.0.0.1:8082:8081
    environment:
      - DATABASE_URL=mysql://root:admin@db:3306/eco-planner
      - IRON_SESSION_PASSWORD=mt6EAckefnuUpKKzLG7Rr8mQJVkmvJ3j
    env_file:
      - .env.test.local
    depends_on:
      db:
        condition: service_healthy
    command: sh -c 'yarn prisma migrate reset -f' # Seed the database

  test:
    image: ecoplanner:test
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    networks:
      - test_network
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    environment:
      - TEST_BASE_URL=http://web:8081
      - CI=true # For playwright config
    depends_on:
      web:
        condition: service_started
    command: sh -c 'yarn test'

networks:
  test_network:
    internal: true
