name: eco-planner:test

services:
  db:
    build:
      context: .
      dockerfile: docker/testdb.Dockerfile
    networks:
      - test_network
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-padmin" ]
      interval: 2s
      timeout: 30s
      retries: 10

  web:
    image: ecoplanner:web
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        BUILDKIT_INLINE_CACHE: 1
    networks:
      - default
      - test_network
    ports:
      - 127.0.0.1:8082:3000
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://root:admin@db:3306/eco-planner
      - IRON_SESSION_PASSWORD=mt6EAckefnuUpKKzLG7Rr8mQJVkmvJ3j
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "yarn", "test:health", "-p", "3000" ]
      interval: 2s
      timeout: 30s
      retries: 10
    command: sh -c 'yarn prisma migrate reset -f && node .next/standalone/server.js' # Seed the database

  test:
    image: ecoplanner:test
    pull_policy: build
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    networks:
      - default
      - test_network
    environment:
      - TEST_BASE_URL=http://web:3000
      - CI=true # For playwright config
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
    depends_on:
      web:
        condition: service_healthy
    restart: "no"

networks:
  test_network:
    internal: true
