name: eco-planner

services:
  app:
    image: ecoplanner:latest
    build:
      context: .
      args:
        GIT_LONG_HASH: ${GIT_LONG_HASH}
    pull_policy: build
    ports:
      - 127.0.0.1:8081:8081
    expose:
      - 8081
    # env_file:
      # - docker/.env
    command: sh -c 'HOSTNAME="0.0.0.0" node server.js'
