name: Eco Planner Test Suite

services:
  run_tests:
    networks:
      - testing_network

  db:
    networks:
      - testing_network

  app:
    networks:
      - testing_network

networks:
  testing_network:
    internal: true