name: eco-planner-test-suite

services:
  run_tests:
    pull_policy: build
    build: 
      context: ..
      dockerfile: docker/testing.Dockerfile
    image: eco-planner-testing:latest
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - testing_network
    environment:
      - CI=true
      - TEST_BASE_URL=http://app:8081
    restart: "no"

  db:
    pull_policy: build
    build:
      context: ..
      dockerfile: docker/db.Dockerfile
    image: eco-planner-db:latest
    networks:
      - testing_network
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=eco-planner
    # Debugging locally. Also switch to `internal: false`
    # ports:
    #   - "3366:3306"

  db_seed:
    pull_policy: build
    build:
      context: ..
      dockerfile: docker/db-seed.Dockerfile
    image: eco-planner-db-seed:latest
    depends_on:
      db:
        condition: service_healthy
    networks:
      - testing_network
    environment:
      - DATABASE_URL=mysql://root:admin@db:3306/eco-planner
    restart: "no"

  app:
    pull_policy: build
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    image: eco-planner-app:latest
    depends_on:
      db:
        condition: service_healthy
      db_seed:
        condition: service_completed_successfully
    networks:
      - testing_network
      - default
    ports:
      - "8081:8081"
    environment:
      - IRON_SESSION_PASSWORD=7LSP6h4CNt9MKjgzxemgvbqQxb6ud5SMaLFfLLBbHxHb9BH7tK79nTmEvs6724kg
      - DATABASE_URL=mysql://root:admin@db:3306/eco-planner
      - SKIP_MAIL_SELF_TEST=true
      - BASE_URL=http://localhost:8081

networks:
  testing_network:
    # Swap these to access the database from outside the Docker network 
    internal: true
    # internal: false