name: eco-planner-test-suite

services:
  tests:
    image: eco-planner-testing:test
    pull_policy: build
    build: 
      context: ..
      dockerfile: docker/testing.Dockerfile
    restart: "no"
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - default
      - testing_network
    environment:
      - TEST_BASE_URL=${TEST_BASE_URL:-http://app:8081}

  db:
    image: mariadb:lts
    restart: always
    networks:
      # - default
      - testing_network
    # For debugging locally you can uncomment the port mapping below and the default network above,
    # allowing you to access the database from your host machine at localhost:3366.
    # ports:
    #   - "3366:3306"
    volumes:
      - testing_data:/mariadb
    environment:
      - MARIADB_DATABASE=${TEST_MARIADB_DATABASE:-eco-planner}
      - MARIADB_ROOT_PASSWORD=${TEST_MARIADB_ROOT_PASSWORD:-admin}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 5s
      interval: 15s
      timeout: 5s
      retries: 10

  db_seed:
    image: eco-planner-db-seed:test
    pull_policy: build
    build:
      context: ..
      dockerfile: docker/db-seed.Dockerfile
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - testing_network
    environment:
      - DATABASE_URL=${TEST_DATABASE_URL:-mysql://root:admin@db:3306/eco-planner}

  app:
    image: eco-planner-app:test
    pull_policy: build
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      db_seed:
        condition: service_completed_successfully
    networks:
      - default
      - testing_network
    ports:
      - "8081:8081"
    environment:
      # Database connection string
      - DATABASE_URL=${TEST_DATABASE_URL:-mysql://root:admin@db:3306/eco-planner}
      # Iron session cookie encryption password
      - IRON_SESSION_PASSWORD=${TEST_IRON_SESSION_PASSWORD:-7LSP6h4CNt9MKjgzxemgvbqQxb6ud5SMaLFfLLBbHxHb9BH7tK79nTmEvs6724kg}
      # Used to connect mailClient to SMTP server
      - MAIL_HOST=${TEST_MAIL_HOST}
      - MAIL_USER=${TEST_MAIL_USER}
      - MAIL_PASSWORD=${TEST_MAIL_PASSWORD}
      # Used for links in emails and as canonical url in meta tags
      - BASE_URL=${TEST_BASE_URL:-http://app:8081}

  # Shuts down the stack after tests are completed
  cleanup:
    image: docker:cli
    pull_policy: build
    restart: "no"
    depends_on:
      tests:
        condition: service_completed_successfully
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "
        echo 'Tests completed, shutting down stack...' &&
        docker compose -p eco-planner-test-suite kill -s SIGTERM app db
      "

networks:
  testing_network:
    internal: true

volumes:
  testing_data:
    driver: local