name: eco-planner-staging-build

services:
  db:
    pull_policy: build
    build:
      context: ..
      dockerfile: docker/db.Dockerfile
    image: eco-planner-db:dev
    networks:
      - staging_network
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=eco-planner
    restart: always

  db_seed:
    pull_policy: build
    build:
      context: ..
      dockerfile: docker/db-seed.Dockerfile
    image: eco-planner-db-seed:dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - staging_network
    environment:
      - DATABASE_URL=mysql://root:admin@db:3306/eco-planner
    restart: "no"

  app:
    pull_policy: build
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    image: eco-planner-app:dev
    depends_on:
      db:
        condition: service_healthy
      db_seed:
        condition: service_completed_successfully
    networks:
      - staging_network
      - default
    ports:
      - "8081:8081"
    environment:
      - IRON_SESSION_PASSWORD=7LSP6h4CNt9MKjgzxemgvbqQxb6ud5SMaLFfLLBbHxHb9BH7tK79nTmEvs6724kg
      - DATABASE_URL=mysql://root:admin@db:3306/eco-planner
      - SKIP_MAIL_SELF_TEST=true
      - BASE_URL=http://localhost:8081
    restart: always

networks:
  staging_network:
    internal: true