name: eco-planner-test-suite

services:
  run_tests:
    image: eco-planner-testing:test
    pull_policy: build
    build: 
      context: ..
      dockerfile: docker/testing.Dockerfile
    restart: no
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - default
      - testing_network
    environment:
      - TEST_BASE_URL=http://app:8081

  db:
    image: mariadb:lts
    restart: always
    networks:
      # - default
      - testing_network
    # For debugging locally you can uncomment the port mapping below and the default network above,
    # allowing you to access the database from your host machine at localhost:3366.
    # ports:
    #   - "3366:3306"
    volumes:
      - testing_data:/mariadb
    environment:
      - MARIADB_DATABASE=eco-planner
      - MARIADB_ROOT_PASSWORD=admin
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 5s
      interval: 15s
      timeout: 5s
      retries: 10

  db_seed:
    image: eco-planner-db-seed:test
    pull_policy: build
    build:
      context: ..
      dockerfile: docker/db-seed.Dockerfile
    restart: no
    depends_on:
      db:
        condition: service_healthy
    networks:
      - testing_network
    environment:
      - DATABASE_URL=mysql://root:admin@db:3306/eco-planner

  app:
    image: eco-planner-app:test
    pull_policy: build
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      db_seed:
        condition: service_completed_successfully
    networks:
      - default
      - testing_network
    ports:
      - "8081:8081"
    environment:
      - IRON_SESSION_PASSWORD=7LSP6h4CNt9MKjgzxemgvbqQxb6ud5SMaLFfLLBbHxHb9BH7tK79nTmEvs6724kg
      - DATABASE_URL=mysql://root:admin@db:3306/eco-planner
      - SKIP_MAIL_SELF_TEST=true
      - BASE_URL=http://localhost:8081

networks:
  testing_network:
    internal: true

volumes:
  testing_data:
    driver: local