name: eco-planner-test-suite

services:
  run_tests:
    build: 
      context: ..
      dockerfile: docker/testing.Dockerfile
    image: eco-planner-testing:latest
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - testing_network
    environment:
      - CI=true
      - TEST_BASE_URL=http://app:8081

  db:
    build:
      context: ..
      dockerfile: docker/db.Dockerfile
    image: eco-planner-db:latest
    networks:
      - testing_network
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=eco-planner

  app:
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    image: eco-planner-app:latest
    depends_on:
      db:
        condition: service_healthy
    networks:
      - testing_network
      - default
    ports:
      - "8081:8081"
    environment:
      - IRON_SESSION_PASSWORD=7LSP6h4CNt9MKjgzxemgvbqQxb6ud5SMaLFfLLBbHxHb9BH7tK79nTmEvs6724kg
      - DATABASE_URL=mysql://root:admin@db:3306/eco-planner
      - SKIP_MAIL_SELF_TEST=true
      - BASE_URL=http://localhost:8081

networks:
  testing_network:
    internal: true 