export const colors = {
  /* Text modifiers */
  reset: (text: string) => `\x1b[0m${text}\x1b[0m`,
  bold: (text: string) => `\x1b[1m${text}\x1b[0m`,
  dim: (text: string) => `\x1b[2m${text}\x1b[0m`,
  italic: (text: string) => `\x1b[3m${text}\x1b[0m`,
  underline: (text: string) => `\x1b[4m${text}\x1b[0m`,
  overline: (text: string) => `\x1b[53m${text}\x1b[0m`,
  strikethrough: (text: string) => `\x1b[9m${text}\x1b[0m`,
  /* Text colors */
  black: (text: string) => `\x1b[30m${text}\x1b[0m`,
  red: (text: string) => `\x1b[31m${text}\x1b[0m`,
  green: (text: string) => `\x1b[32m${text}\x1b[0m`,
  yellow: (text: string) => `\x1b[33m${text}\x1b[0m`,
  blue: (text: string) => `\x1b[34m${text}\x1b[0m`,
  magenta: (text: string) => `\x1b[35m${text}\x1b[0m`,
  cyan: (text: string) => `\x1b[36m${text}\x1b[0m`,
  white: (text: string) => `\x1b[37m${text}\x1b[0m`,
  gray: (text: string) => colors.blackBright(text),
  defaultFG: (text: string) => `\x1b[39m${text}\x1b[0m`,
  /* Bright text colors */
  blackBright: (text: string) => `\x1b[90m${text}\x1b[0m`,
  redBright: (text: string) => `\x1b[91m${text}\x1b[0m`,
  greenBright: (text: string) => `\x1b[92m${text}\x1b[0m`,
  yellowBright: (text: string) => `\x1b[93m${text}\x1b[0m`,
  blueBright: (text: string) => `\x1b[94m${text}\x1b[0m`,
  magentaBright: (text: string) => `\x1b[95m${text}\x1b[0m`,
  cyanBright: (text: string) => `\x1b[96m${text}\x1b[0m`,
  whiteBright: (text: string) => `\x1b[97m${text}\x1b[0m`,
  /* Background Colors */
  blackBG: (text: string) => `\x1b[40m${text}\x1b[0m`,
  redBG: (text: string) => `\x1b[41m${text}\x1b[0m`,
  greenBG: (text: string) => `\x1b[42m${text}\x1b[0m`,
  yellowBG: (text: string) => `\x1b[43m${text}\x1b[0m`,
  blueBG: (text: string) => `\x1b[44m${text}\x1b[0m`,
  magentaBG: (text: string) => `\x1b[45m${text}\x1b[0m`,
  cyanBG: (text: string) => `\x1b[46m${text}\x1b[0m`,
  whiteBG: (text: string) => `\x1b[47m${text}\x1b[0m`,
  grayBG: (text: string) => `\x1b[100m${text}\x1b[0m`,
  defaultBG: (text: string) => `\x1b[49m${text}\x1b[0m`,
  /* Bright background colors */
  blackBrightBG: (text: string) => `\x1b[100m${text}\x1b[0m`,
  redBrightBG: (text: string) => `\x1b[101m${text}\x1b[0m`,
  greenBrightBG: (text: string) => `\x1b[102m${text}\x1b[0m`,
  yellowBrightBG: (text: string) => `\x1b[103m${text}\x1b[0m`,
  blueBrightBG: (text: string) => `\x1b[104m${text}\x1b[0m`,
  magentaBrightBG: (text: string) => `\x1b[105m${text}\x1b[0m`,
  cyanBrightBG: (text: string) => `\x1b[106m${text}\x1b[0m`,
  whiteBrightBG: (text: string) => `\x1b[107m${text}\x1b[0m`,
  /* Custom code */
  /** @param code ANSI escape code. https://en.wikipedia.org/wiki/ANSI_escape_code */
  custom: (code: number, text: string) => `\x1b[${code}m${text}\x1b[0m`,
  rgb: (r: number, g: number, b: number, text: string) => `\x1b[38;2;${r};${g};${b}m${text}\x1b[0m`,
  rgbBG: (r: number, g: number, b: number, text: string) => `\x1b[48;2;${r};${g};${b}m${text}\x1b[0m`,
}